### ISSUE TITLE
PlaneNotifier in windows 10

### ISSUE THREAD

**Issue by graememilne** [ravenstx/PlaneNotifier#2]
Well that was a huge learning curve this afternoon .
Lots of googling .
Install Git for windows (Git CMD then watched a video about GIT ,installed GIT BASH)
Followed the tutorial on how to alter a file (planenotifier.py)
Commands to use are slightly different to linux.
Saved /closed file .
Then did, python  planenotifer.py

The screen capture shows what i have.

How do i get the .

Just away to say ,How do i get the screen notification and it popped up as per screen capture .

![SCreen notification](https://user-images.githubusercontent.com/19634301/222512487-00972761-2b2d-465d-a872-ffe0d3e1f0f4.JPG)

So looks like it is working the way it should.

Regards
Graeme

**Comment by graememilne** [comment]
Does it save a log file with the aircraft detected ,would be cool if it did ???
Thank you 
Regards
Graeme

**Comment by ravenstx** [comment]
Good to see it running, an altitude of 0 meters??, you live near an airport? that would make sense.
if that's the case let me know if you see weird behavior with planes on the ground, i could see a problem with that.
Currently, I've got my hands dirty with other projects but I am planning to make some changes soon.
Also you can delete the first image, its showing you're coordinates.

**Comment by graememilne** [comment]
Ah altitude think i have missed something there .
Is this my location altitude i have to adjust ??
If so where do i find this ??
I am about 4-5 km from the airport.

Have deleted the first image

While testing i noticed this timeout .
It could be that at a certain time the A/C count can be low at this time of
evening.
Where no A/C are in the area .
Will check tomorrow when it gets busy in the morning .
Helis going to and from the rigs and arrivals departures of aircraft .

**Comment by graememilne** [comment]
Unfortunately there was a timeout this morning 
Even with plenty a/c movement

**Comment by ravenstx** [comment]
I made some changes in the flightdetector.py file to handle those errors.
Now the program will continue to run after a timeout error.

**Comment by graememilne** [comment]
OK,thank you very much
I'll go delete the screen capture I sent you like yesterday.
Will go and test it.

**Comment by graememilne** [comment]
The changes you made to the flightdetector.py file has worked.
No time out errors now.
Thank you very much
